FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./
COPY apps ./apps
COPY packages ./packages

# Install dependencies at root (workspaces)
RUN npm install

# Generate Prisma client
RUN npm run generate-prisma

# Build the user-app Next.js app directly (it will compile the packages it needs)
RUN npm run build --workspace=user-app

# Expose the port
EXPOSE 3000

# Start the app
CMD ["npm", "run", "start-user-app"]